### PR TITLE
Fix compatibility with GCC 10.

### PR DESCRIPTION
**Pull request by DDoSolitary**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 1

---

GCC 10 defaults to -fno-common, which requires "extern" when defining global variables in headers.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DDoSolitary** [comment]
Tests failed unfortunately... I'll take a look later.

**Comment by DL6ER** [comment]
Tests are all green after restarting the failed ones. There exists a race-collision in the tests leading to false-negative results. I haven't had the time to look at this so far, also because it doesn't happen very often.

**Review by DL6ER — CHANGES_REQUESTED** [review]
Thanks for your submission. I'm slightly surprised I forgot this in only one spot :-)

Can I ask you to add
```
-fno-common
```
also to this line:
https://github.com/pi-hole/FTL/blob/e1db31de09a5177459690118f55513f9d8fad2bd/src/CMakeLists.txt#L44
and add a descriptive comment above like
```
# -fno-common: Emit globals without explicit initializer from `.bss` to `.data`. This causes GCC to reject multiple definitions of global variables. This is the new default from GCC-10 on.
```
to enforce this also in the future to avoid anyone making such a "mistake" again?

**Comment by DDoSolitary** [comment]
@DL6ER Done.

**Comment by DL6ER** [comment]
Thanks, the failing tests should get fixed by https://github.com/pi-hole/FTL/pull/945

**Review by DL6ER — APPROVED** [review]
